"""Custom Kivy recipe — adds --no-isolation to the build command.

python-for-android builds Kivy via `python -m build --wheel`. By default
this creates an isolated pip environment to install build deps. Our Python
was built with --without-ensurepip, so the venv can't bootstrap pip and
setuptools.build_meta fails to import.

--no-isolation bypasses the isolated env and uses the p4a-managed Python
directly, where setuptools is already installed as a recipe dependency.
"""
from pythonforandroid.recipes.kivy import KivyRecipe as _KivyRecipe


class KivyRecipe(_KivyRecipe):
    extra_build_args = ['--no-isolation']

    def prebuild_arch(self, arch):
        super().prebuild_arch(arch)
        import os
        # Kivy's setup.py calls get_extensions_from_sources() at module level
        # which checks that config.pxi exists BEFORE build_extensions() generates
        # it. On a first build, config.pxi doesn't exist yet, causing the error:
        #   "Dependency for context.pyx not resolved: config.pxi"
        # Pre-generate config.pxi with the known Android+SDL2 values so the
        # dependency check passes. build_extensions() will overwrite it with the
        # same content anyway.
        include_dir = os.path.join(self.get_build_dir(arch.arch), 'kivy', 'include')
        config_pxi_path = os.path.join(include_dir, 'config.pxi')
        if os.path.exists(config_pxi_path):
            return  # already generated from a previous build or by build_extensions
        os.makedirs(include_dir, exist_ok=True)
        content = (
            '# Autogenerated by custom p4a recipe (Android+SDL2 preset)\n'
            'DEF PY3 = 1\n'
            'DEF USE_RPI_VIDCORE_LITE = 0\n'
            'DEF USE_EGL = 0\n'
            'DEF USE_OPENGL_ES2 = 1\n'
            'DEF USE_OPENGL_MOCK = 0\n'
            'DEF USE_SDL2 = 1\n'
            'DEF USE_PANGOFT2 = 0\n'
            'DEF USE_IOS = 0\n'
            'DEF USE_ANDROID = 1\n'
            'DEF USE_MESAGL = 0\n'
            'DEF USE_X11 = 0\n'
            'DEF USE_WAYLAND = 0\n'
            'DEF USE_GSTREAMER = 0\n'
            'DEF USE_AVFOUNDATION = 0\n'
            'DEF USE_OSX_FRAMEWORKS = 0\n'
            'DEF DEBUG_GL = 0\n'
            'DEF KIVY_SDL_GL_ALPHA_SIZE = 8\n'
            'DEF DEBUG = 0\n'
            'DEF PLATFORM = "android"\n'
        )
        with open(config_pxi_path, 'w') as f:
            f.write(content)
        print(f'Pre-generated {config_pxi_path}')


recipe = KivyRecipe()
